{
 "title": "Air Quality",
 "description": "Default Purple_Exporter Display Panel",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Estimated Mass Concentrations (A)",
   "type": "timeseries",
   "description": "Estimate mass concentration of particles < X uM in diameter at Sensor A",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "PM_1_0_A", "legendFormat": "Con. < 1.0 uM" },
    { "expr": "PM_2_0_A", "legendFormat": "Con. < 2.0 uM" },
    { "expr": "PM_10_0_A", "legendFormat": "Con. < 10.0 uM" }
   ]
  },
  {
   "title": "Estimated Mass Concentrations (B)",
   "type": "timeseries",
   "description": "Estimated Mass Concentration of Particles < X uM in diameter at Sensor B",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "PM_1_0_B", "legendFormat": "Con. < 1.0 uM" },
    { "expr": "PM_2_0_B", "legendFormat": "Con. < 2.0 uM" },
    { "expr": "PM_10_0_B", "legendFormat": "Con. < 10.0 uM" }
   ]
  },
  {
   "title": "Particle Count (A)",
   "type": "timeseries",
   "description": "Count of Particles greater than X uM in diameter at Sensor A",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "Count_0_3_A", "legendFormat": "Count >= 0.3 uM" },
    { "expr": "Count_0_5_A", "legendFormat": "Count >= 0.5 uM" },
    { "expr": "Count_1_0_A", "legendFormat": "Count >= 1.0 uM" },
    { "expr": "Count_2_5_A", "legendFormat": "Count >= 2.5 uM" },
    { "expr": "Count_5_0_A", "legendFormat": "Count >= 5.0 uM" },
    { "expr": "Count_10_0_A", "legendFormat": "Count >= 10.0 uM" }
   ]
  },
  {
   "title": "Particle Count (B)",
   "type": "timeseries",
   "description": "Count of Particles greater than X uM in diameter for Sensor B",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "Count_0_3_B", "legendFormat": "Count >= 0.3 uM" },
    { "expr": "Count_0_5_B", "legendFormat": "Count >= 0.5 uM" },
    { "expr": "Count_1_0_B", "legendFormat": "Count >= 1.0 uM" },
    { "expr": "Count_2_5_B", "legendFormat": "Count >= 2.5 uM" },
    { "expr": "Count_5_0_B", "legendFormat": "Count >= 5.0 uM" },
    { "expr": "Count_10_0_B", "legendFormat": "Count >= 10.0 uM" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "description": "Air Humidity at sensor",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Humidity" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "description": "Air Temperature at Sensor",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Temperature" }
   ]
  },
  {
   "title": "Air Pressure",
   "type": "stat",
   "description": "Air Pressure at Sensor",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Pressure" }
   ]
  }
 ]
}